clang-tidy: delete default constructor
Default constructor was invalid for class semantics and caused
clang-tidy/Clang diagnostics. Mark the default constructor as
`=delete` to prevent accidental default construction and keep
-Werror builds green. No functional changes.

'''
../sensor.hpp:52:13: error: explicitly defaulted move assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
   52 |     Sensor& operator=(Sensor&&) = default;
'''

Change-Id: I2d8ac6cf10afc4976550ac66eb5c64896a1354cf
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>